"""Alembic migration pipeline: state, upgrade, downgrade, re-upgrade, and drift."""

import shutil

import pytest
from alembic import command
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, Integer, Table, create_engine, inspect, pool

from app.models import Base
from tests.conftest import PROJECT_ROOT, make_alembic_config

pytestmark = pytest.mark.integration

BASELINE = "0001"
HEAD = "0008"  # Stage 6: audit trail and session hardening
HISTORY = ["0008", "0007", "0006", "0005", "0004", "0003", "0002", "0001"]


def current_revision(database_url: str) -> str | None:
    engine = create_engine(database_url, poolclass=pool.NullPool)
    try:
        with engine.connect() as connection:
            return MigrationContext.configure(connection).get_current_revision()
    finally:
        engine.dispose()


def table_names(database_url: str) -> set[str]:
    engine = create_engine(database_url, poolclass=pool.NullPool)
    try:
        return set(inspect(engine).get_table_names())
    finally:
        engine.dispose()


@pytest.fixture
def restore_head(alembic_config):
    """Whatever a test does to the schema, leave the test database at head."""
    yield
    command.upgrade(alembic_config, "head")


# --- migration state -------------------------------------------------------


def test_env_py_targets_application_metadata(migrated_database, alembic_config):
    """A table added to Base.metadata must be seen by autogenerate through env.py."""
    probe = Table("stage0_metadata_probe", Base.metadata, Column("id", Integer, primary_key=True))
    try:
        with pytest.raises(AutogenerateDiffsDetected, match="stage0_metadata_probe"):
            command.check(alembic_config)
    finally:
        Base.metadata.remove(probe)


def test_history_is_linear_with_single_head(alembic_config):
    script = ScriptDirectory.from_config(alembic_config)
    assert script.get_heads() == [HEAD]
    assert script.get_bases() == [BASELINE]
    assert [r.revision for r in script.walk_revisions()] == HISTORY


def test_every_revision_defines_upgrade_and_downgrade(alembic_config):
    script = ScriptDirectory.from_config(alembic_config)
    for revision in script.walk_revisions():
        assert callable(getattr(revision.module, "upgrade", None)), revision.revision
        assert callable(getattr(revision.module, "downgrade", None)), revision.revision


def test_database_is_at_head(test_database_url, migrated_database, alembic_config):
    head = ScriptDirectory.from_config(alembic_config).get_current_head()
    assert current_revision(test_database_url) == head


def test_models_and_migrations_have_no_drift(migrated_database, alembic_config):
    """Equivalent of `alembic check`: autogenerate finds nothing to migrate."""
    command.check(alembic_config)


def test_head_creates_only_expected_tables(test_database_url, migrated_database):
    domain = {
        "patients", "encounters", "observations", "conditions", "allergies", "clinical_notes",
        "lab_orders", "lab_samples", "lab_results", "reports", "prescriptions", "prescription_items",
        "departments", "staff", "appointments", "admissions", "admission_transfers", "workflow_tasks",
        "users", "roles", "permissions", "role_permissions", "user_roles", "auth_sessions",
        "audit_events",
    }
    assert table_names(test_database_url) == {"alembic_version"} | domain
    assert set(Base.metadata.tables) == domain


# --- upgrade / downgrade / re-upgrade --------------------------------------


def test_upgrade_downgrade_upgrade_cycle(test_database_url, alembic_config, restore_head):
    command.upgrade(alembic_config, "head")
    assert current_revision(test_database_url) == HEAD

    command.downgrade(alembic_config, "base")
    assert current_revision(test_database_url) is None
    assert table_names(test_database_url) == {"alembic_version"}

    command.upgrade(alembic_config, "head")
    assert current_revision(test_database_url) == HEAD


def test_upgrade_is_idempotent_at_head(test_database_url, alembic_config):
    command.upgrade(alembic_config, "head")
    command.upgrade(alembic_config, "head")
    assert current_revision(test_database_url) == HEAD


def test_offline_sql_generation(alembic_config, capsys):
    command.upgrade(alembic_config, "head", sql=True)
    sql = capsys.readouterr().out
    assert "alembic_version" in sql
    assert f"'{HEAD}'" in sql


def test_unknown_revision_is_rejected(alembic_config):
    with pytest.raises(Exception, match="nonexistent"):
        command.upgrade(alembic_config, "nonexistent")


# --- DDL through the real env.py -------------------------------------------

PROBE_REVISION_TEMPLATE = '''"""test-only probe revision"""
from alembic import op
import sqlalchemy as sa

revision = "9001"
down_revision = "{head}"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "stage0_migration_probe",
        sa.Column("id", sa.Integer, primary_key=True),
    )


def downgrade() -> None:
    op.drop_table("stage0_migration_probe")
'''


def test_env_py_executes_and_reverses_real_ddl(tmp_path, test_database_url, restore_head):
    """Runs the project's env.py + real history with a throwaway revision that creates a table.

    Proves that DDL issued by a migration is actually committed on upgrade and removed
    on downgrade. The probe revision lives only in a temp directory; the project's own
    migration history is untouched.
    """
    script_dir = tmp_path / "alembic"
    (script_dir / "versions").mkdir(parents=True)
    shutil.copy(PROJECT_ROOT / "alembic" / "env.py", script_dir / "env.py")
    shutil.copy(PROJECT_ROOT / "alembic" / "script.py.mako", script_dir / "script.py.mako")
    for revision_file in (PROJECT_ROOT / "alembic" / "versions").glob("*.py"):
        shutil.copy(revision_file, script_dir / "versions" / revision_file.name)
    probe = PROBE_REVISION_TEMPLATE.replace("{head}", HEAD)
    (script_dir / "versions" / "9001_probe.py").write_text(probe, encoding="utf-8")
    probe_config = make_alembic_config(test_database_url, script_location=script_dir)

    try:
        command.upgrade(probe_config, "9001")
        assert current_revision(test_database_url) == "9001"
        assert "stage0_migration_probe" in table_names(test_database_url)

        command.downgrade(probe_config, HEAD)
        assert current_revision(test_database_url) == HEAD
        assert "stage0_migration_probe" not in table_names(test_database_url)
    finally:
        # Never leave the probe revision recorded in the test database.
        if current_revision(test_database_url) == "9001":
            command.downgrade(probe_config, HEAD)
