"""Configurable LLM provider registry (Stage 7).

The rest of the HMS only sees a LangChain `BaseChatModel`. Providers are registered by name;
adding one later (another vendor, a local model) means adding a builder here and a value to
LLM_PROVIDER - no change to the graph, tools, guardrails or API.

    LLM_PROVIDER=gemini     ChatGoogleGenerativeAI (LangChain), model LLM_MODEL, key GEMINI_API_KEY
    LLM_PROVIDER=openrouter ChatOpenAI (LangChain) against OpenRouter's OpenAI-compatible API,
                            model LLM_MODEL, key OPENROUTER_API_KEY, endpoint OPENROUTER_BASE_URL
    LLM_PROVIDER=fake       DeterministicClinicalModel: offline, reproducible (tests, local dev)
    LLM_PROVIDER=disabled   the assistant reports itself unavailable (HTTP 503)

Privacy: LangChain can forward prompts to third-party tracing (LangSmith) when tracing env
vars are set. `disable_external_tracing()` switches that off unless AI_ALLOW_EXTERNAL_TRACING.
"""

import json
import os
import re
from collections.abc import Callable
from typing import Any

from langchain_core.callbacks import CallbackManagerForLLMRun
from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage
from langchain_core.outputs import ChatGeneration, ChatResult
from pydantic import Field

from app.core.config import Settings

TRACING_ENV_VARS = ("LANGSMITH_TRACING", "LANGCHAIN_TRACING_V2", "LANGCHAIN_TRACING")


class AIUnavailableError(RuntimeError):
    """The assistant is disabled or not configured (e.g. no API key)."""


def disable_external_tracing(settings: Settings) -> None:
    if not settings.ai_allow_external_tracing:
        for name in TRACING_ENV_VARS:
            os.environ[name] = "false"


# --- deterministic models (no network) --------------------------------------------------------

_EVIDENCE_BLOCK = re.compile(r"<evidence>\s*(\[.*?\])\s*</evidence>", re.S)
_CONTEXT_BLOCK = re.compile(r"<request>\s*(\{.*?\})\s*</request>", re.S)


_RISK_BLOCK = re.compile(r"<risk_context>\s*(\{.*?\})\s*</risk_context>", re.S)


def _deterministic_risk_answer(base: dict, risk: dict, clinical: list[dict]) -> dict:
    """FOUR_DAY_RISK (Stage 8): echo the horizon, explain every computed signal as a potential concern."""
    signals = risk["signals"]
    horizon = {key: risk[key] for key in ("reference_at", "horizon_start", "horizon_end", "analysis_horizon_days")}
    limitations = ["Generated by the deterministic offline model; not clinical reasoning.",
                   "Signal rules are illustrative and not clinically validated.", *risk["data_gaps"][:8]]
    if not clinical:
        return {**base, **horizon, "status": "ABSTAIN", "summary": "", "risk_signals": [], "observed_trends": [],
                "evidence": [], "limitations": limitations, "precautionary_suggestions": [],
                "abstain_reason": "insufficient clinical evidence"}
    cited = list(dict.fromkeys(e for s in signals for e in s["evidence"]))[:40] or [e["source_id"] for e in clinical[:3]]
    summary = (f"The demonstration rule set identified {len(signals)} potential risk signal(s) that may warrant "
               "clinical review over the next 4 days." if signals else
               "The demonstration rule set identified no potential risk signals in the available evidence; "
               "this does not indicate low risk.")
    return {**base, **horizon, "status": "ANALYSIS", "summary": summary,
            "risk_signals": [{"signal_id": s["signal_id"], "category": s["category"], "priority": s["priority"],
                              "explanation": f"Potential concern that may warrant clinical review: {s['detail']}",
                              "evidence": s["evidence"]} for s in signals],
            "observed_trends": [{"description": f"Possible pattern: {s['title']}.", "evidence": s["evidence"]}
                                for s in signals if s["category"] == "VITAL_TREND"],
            "evidence": [{"source_id": source_id, "relevance": "supports a computed signal" if signals
                          else "recent record considered"} for source_id in cited],
            "limitations": limitations,
            "precautionary_suggestions": ["Clinician may wish to review the cited records and verify the flagged "
                                          "readings." if signals else "Clinician may wish to review the most recent "
                                          "records."],
            "abstain_reason": None}


class DeterministicClinicalModel(BaseChatModel):
    """Reproducible stand-in for an LLM: reads the evidence in the prompt and returns a valid,
    fully-cited, review-oriented JSON analysis (or abstains when there is no evidence).
    It never invents sources, so it exercises the real validation path end to end."""

    @property
    def _llm_type(self) -> str:
        return "hms-deterministic-fake"

    def _generate(self, messages: list[BaseMessage], stop=None, run_manager: CallbackManagerForLLMRun | None = None,
                  **kwargs: Any) -> ChatResult:
        prompt = "\n".join(str(m.content) for m in messages)
        context = json.loads(_CONTEXT_BLOCK.search(prompt).group(1))
        evidence = json.loads(_EVIDENCE_BLOCK.search(prompt).group(1))
        clinical = [e for e in evidence if e["type"] != "patient"]
        base = {"analysis_type": context["analysis_type"], "patient_reference": context["patient_number"],
                "requires_human_review": True}
        risk = _RISK_BLOCK.search(prompt)
        if risk:
            answer = _deterministic_risk_answer(base, json.loads(risk.group(1)), clinical)
        elif not clinical:
            answer = {**base, "status": "ABSTAIN", "analysis": "", "evidence": [],
                      "limitations": ["No clinical records were available for this patient."],
                      "review_suggestions": [], "abstain_reason": "insufficient clinical evidence"}
        else:
            counts: dict[str, int] = {}
            for item in clinical:
                counts[item["type"]] = counts.get(item["type"], 0) + 1
            summary = ", ".join(f"{n} {kind.replace('_', ' ')} record(s)" for kind, n in sorted(counts.items()))
            cited = clinical[:3]
            answer = {**base, "status": "ANALYSIS",
                      "analysis": f"Deterministic test analysis based on {summary}.",
                      "evidence": [{"source_id": e["source_id"], "relevance": f"{e['type']} considered"} for e in cited],
                      "limitations": ["Generated by the deterministic offline model; not clinical reasoning."],
                      "review_suggestions": ["Clinician to review the cited records and recent trends."],
                      "abstain_reason": None}
        return ChatResult(generations=[ChatGeneration(message=AIMessage(content=json.dumps(answer)))])


class ScriptedChatModel(BaseChatModel):
    """Returns pre-set raw texts in order (tests: malformed output, unsafe output, injection echoes).
    Records every prompt it receives so tests can inspect exactly what the model was shown."""

    responses: list[str]
    prompts: list[str] = Field(default_factory=list)

    @property
    def _llm_type(self) -> str:
        return "hms-scripted-fake"

    def _generate(self, messages: list[BaseMessage], stop=None, run_manager=None, **kwargs: Any) -> ChatResult:
        self.prompts.append("\n".join(str(m.content) for m in messages))
        text = self.responses.pop(0) if len(self.responses) > 1 else self.responses[0]
        return ChatResult(generations=[ChatGeneration(message=AIMessage(content=text))])


# --- registry ---------------------------------------------------------------------------------


def _gemini(settings: Settings) -> BaseChatModel:
    if settings.gemini_api_key is None or not settings.gemini_api_key.get_secret_value():
        raise AIUnavailableError("GEMINI_API_KEY is not configured.")
    from langchain_google_genai import ChatGoogleGenerativeAI

    return ChatGoogleGenerativeAI(
        model=settings.llm_model,
        google_api_key=settings.gemini_api_key.get_secret_value(),
        temperature=settings.llm_temperature,
        max_output_tokens=settings.llm_max_output_tokens,
        timeout=settings.llm_timeout_seconds,
        max_retries=1,
        response_mime_type="application/json",  # native JSON mode; the schema is still validated by us
    )


def _openrouter(settings: Settings) -> BaseChatModel:
    """OpenRouter (OpenAI-compatible). No provider-side JSON-schema mode is requested (not every OpenRouter
    model supports `response_format`); the output contract is enforced by the application's own parsing,
    schema, grounding and semantic validation, exactly as for every other provider."""
    if settings.openrouter_api_key is None or not settings.openrouter_api_key.get_secret_value().strip():
        raise AIUnavailableError("OPENROUTER_API_KEY is not configured.")
    from langchain_openai import ChatOpenAI

    return ChatOpenAI(
        model=settings.llm_model,
        api_key=settings.openrouter_api_key,  # SecretStr: stays out of repr/logs
        base_url=settings.openrouter_base_url,
        temperature=settings.llm_temperature,
        max_tokens=settings.llm_max_output_tokens,
        timeout=settings.llm_timeout_seconds,
        max_retries=1,
    )


def _fake(settings: Settings) -> BaseChatModel:
    return DeterministicClinicalModel()


def _disabled(settings: Settings) -> BaseChatModel:
    raise AIUnavailableError("The AI assistant is disabled (LLM_PROVIDER=disabled).")


PROVIDERS: dict[str, Callable[[Settings], BaseChatModel]] = {
    "gemini": _gemini,
    "openrouter": _openrouter,
    "fake": _fake,
    "disabled": _disabled,
}


ModelFactory = Callable[[], BaseChatModel]


def build_model_factory(settings: Settings) -> ModelFactory:
    """A factory (not a model) so a misconfigured provider only affects AI requests, not startup."""
    disable_external_tracing(settings)
    builder = PROVIDERS[settings.llm_provider]
    return lambda: builder(settings)


def model_is_configured(settings: Settings) -> bool:
    try:
        PROVIDERS[settings.llm_provider](settings)
        return True
    except AIUnavailableError:
        return False


__all__ = ["AIUnavailableError", "DeterministicClinicalModel", "ModelFactory", "PROVIDERS", "ScriptedChatModel",
           "build_model_factory", "disable_external_tracing", "model_is_configured"]
